import { ChatMistralAI } from "@langchain/mistralai";
import { MessagesAnnotation } from "@langchain/langgraph";
import { tools } from "./tools/tools";
import { ChatGoogleGenerativeAI } from "@langchain/google-genai";
import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { Client } from "langsmith";
import { ChatGroq } from "@langchain/groq";
import { ChatOpenAI } from "@langchain/openai";
import { SYSTEM_PROMPT } from "./prompts";

export const llm = new ChatMistralAI({
  apiKey: process.env.MISTRAL_API_KEY,
  model: "mistral-large-latest",
  temperature: 0,
  maxRetries: 2,
}).bindTools(tools);

export const visionLLM = new ChatGoogleGenerativeAI({
  apiKey: process.env.GEMINI_API_KEY,
  model: "gemini-2.0-flash",
  temperature: 0,
  maxRetries: 2,
}).bindTools(tools);

//-------------------------------------
export const langsmithClient = new Client();
//-------------------------------------

//-------------------------------------

export async function callModel(state: typeof MessagesAnnotation.State) {
  const lastMessage = state.messages[state.messages.length - 1];



  // ✅ Extract images properly
  const images: any[] = Array.isArray(lastMessage.additional_kwargs?.images)
    ? lastMessage.additional_kwargs.images
    : [];

  if (images?.length > 0) {


    const message = new HumanMessage({
      content: [
        {
          type: "text",
          text: lastMessage.content,
        },
        {
          type: "image_url",
          image_url: {
            url: images[0],
          },
        },
      ],
    });

    const response = await visionLLM.invoke([
      new SystemMessage(
        "You are an expert agriculture assistant named FarmAI (strictly your name). Your goal is to understand the user's intent and provide the best possible response, You are expert in plant disease diagnosis, if user ask you about your name the reply with your name 'FarmAI' otherwise just straightly answer user's query"
      ),
      message,
    ]);

    return { messages: [response] };
  }



  // The main prompt is now imported directly from prompts.ts.
  const systemMessage = new SystemMessage(SYSTEM_PROMPT);

  // Filter out any existing SystemMessages from state to avoid duplicates
  // (LangGraph's checkpointer can replay old SystemMessages from previous turns)
  const filteredMessages = state.messages.filter(
    (m: any) => !(m instanceof SystemMessage || m._getType?.() === "system")
  );
  const messages = [systemMessage, ...filteredMessages];

  console.log("--- Agent Turn ---");
  console.log("Input Messages Count:", messages.length);
  const lastHuman = messages[messages.length - 1];
  console.log("Last Human Message:", lastHuman.content);

  let response: any;
  let attempts = 0;
  let maxAttempts = 5;
  let delayAmount = 3000;

  while (attempts < maxAttempts) {
    try {
      response = await llm.invoke(messages);
      console.log("Agent Response (Full):", response.content);

      if (response.tool_calls?.length) {
        console.log("\n==================================");
        console.log("🛠️  RAW TOOL CALLS GENERATED BY LLM:");
        console.log("==================================");

        const validIds = new Set<string>();

        response.tool_calls = response.tool_calls.filter((tc: any) => {
          const rawScore = tc.args?.confidence_score;
          const numScore = parseFloat(String(rawScore));
          const isValid = !isNaN(numScore) && numScore >= 0.80;

          console.log(`\n🔍 EVALUATING TOOL: ${tc.name}`);
          console.log(`   └─ Confidence Score Provided: ${rawScore !== undefined ? rawScore : 'MISSING'}`);
          console.log(`   └─ Status: ${isValid ? '✅ APPROVED (>= 0.80)' : '❌ REJECTED (< 0.80)'}`);

          if (isValid) {
            if (tc.id) validIds.add(tc.id);
            // 🛡️ CRITICAL: Remove confidence_score from args so it doesn't break tool validation (Zod)
            if (tc.args) delete tc.args.confidence_score;
          }
          return isValid;
        });

        console.log("\n✅ FINAL FILTERED TOOL CALLS (score stripped):");
        console.log(JSON.stringify(response.tool_calls, null, 2));
        console.log("==================================\n");

        // Sync additional_kwargs for providers that rely on them (like Mistral/OpenAI)
        if (Array.isArray(response.additional_kwargs?.tool_calls)) {
          response.additional_kwargs.tool_calls = response.additional_kwargs.tool_calls
            .filter((rawTc: any) => validIds.has(rawTc.id))
            .map((rawTc: any) => {
              if (rawTc.function?.arguments) {
                try {
                  let args = typeof rawTc.function.arguments === 'string'
                    ? JSON.parse(rawTc.function.arguments)
                    : rawTc.function.arguments;
                  if (args.confidence_score !== undefined) {
                    delete args.confidence_score;
                    rawTc.function.arguments = typeof rawTc.function.arguments === 'string'
                      ? JSON.stringify(args)
                      : args;
                  }
                } catch (e) { }
              }
              return rawTc;
            });
        }
      }
      break; // Success! Break out of the retry loop.
    } catch (err: any) {
      console.error("LLM Error:", err.message);

      if (err.message && (err.message.includes("429") || err.message.includes("Rate limit"))) {
        attempts++;
        if (attempts >= maxAttempts) {
          console.error("❌ Exceeded max retries for rate limits.");
          throw err;
        }
        console.warn(`⏳ Rate limit exceeded (429). Retrying in ${delayAmount / 1000} seconds... (Attempt ${attempts} of ${maxAttempts})`);
        await new Promise(resolve => setTimeout(resolve, delayAmount));
        delayAmount *= 1.5; // Exponential backoff scaling
      } else if (err.message?.includes("empty response") || err.message?.includes("Failed to call a function")) {
        console.warn("Returned an empty response or failed tool call. Falling back.");
        const { AIMessage } = require("@langchain/core/messages");
        response = new AIMessage({
          content: "I'm sorry, I encountered an issue processing your request to fetch prices. Please try asking again or specify your query differently.",
          id: "error-" + Date.now().toString(),
          additional_kwargs: { is_fallback: true },
        });
        break;
      } else {
        throw err;
      }
    }
  }

  return { messages: [response] };
}
